apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ecm3440"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ecm3440"
  template:
    metadata:
      labels:
        app: "ecm3440"
    spec:
      containers:
        - name: "ecm3440"
          image: "dashboard3440.azurecr.io/ecm3440"
          ports:
          - containerPort: 80A

kind: Service
metadata:
    name: "ecm3440"
    labels:
        app: "ecm3440"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ecm3440"