
name: .NET

on:
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Set variables
      run: echo "BUILD_DATE=$(date +%s)" >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: True
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecm3440-dash:${{ env.BUILD_DATE }}, ${{ secrets.DOCKER_HUB_USERNAME }}/ecm3440-dash:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ecm3440-dash:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ecm3440-dash:buildcache,mode=max