
name: .NET

on:
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings "SoilMoistureSensor.Tests/runsettings.xml"
    - name: Copy Coverage to Predictable Location
      run: cp SoilMoistureSensor.Tests/TestResults/*/coverage.info SoilMoistureSensor.Tests/TestResults/coverage.info
    - name: Coverlet coverage test
      uses: b3b00/coverlet-action@1.2.4
      with:
        testProject: 'SoilMoistureSensor.Tests/SoilMoistureSensor.Tests.csproj'
        output: 'SoilMoistureSensor.Tests/TestResults/coverage.info'
        outputFormat: 'lcov'
        excludes: '[program]*,[test]test.*'
        threshold: 10
